import { writeFileSync } from 'fs';
import { join } from 'path';
import { config } from '../config';

export interface DeploymentConfig {
  domain: string;
  email: string;
  port: number;
  dataDir: string;
  workingDir: string;
  user: string;
}

/**
 * Generate Caddyfile for automatic HTTPS and subdomain routing
 */
export function generateCaddyfile(cfg: DeploymentConfig): string {
  return `# dustCMS Caddyfile
# Automatic HTTPS with Let's Encrypt

# Wildcard subdomain for tenants
*.${cfg.domain} {
  reverse_proxy localhost:${cfg.port}

  # HTTPS settings
  tls ${cfg.email}

  # Security headers
  header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    X-XSS-Protection "1; mode=block"
  }

  # Logging
  log {
    output file /var/log/caddy/dustcms-access.log
    format json
  }
}

# Main domain (admin interface)
${cfg.domain} {
  reverse_proxy localhost:${cfg.port}

  # HTTPS settings
  tls ${cfg.email}

  # Security headers
  header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    X-XSS-Protection "1; mode=block"
  }

  # Logging
  log {
    output file /var/log/caddy/dustcms-access.log
    format json
  }
}
`;
}

/**
 * Generate systemd service file for auto-start
 */
export function generateSystemdService(cfg: DeploymentConfig): string {
  return `[Unit]
Description=dustCMS - Multi-tenant Headless CMS
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${cfg.user}
WorkingDirectory=${cfg.workingDir}
ExecStart=${cfg.workingDir}/cms-server
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

# Security settings
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${cfg.dataDir}

# Environment
Environment="NODE_ENV=production"
Environment="PORT=${cfg.port}"
Environment="BASE_DOMAIN=${cfg.domain}"
Environment="DATA_DIR=${cfg.dataDir}"
EnvironmentFile=-${cfg.workingDir}/.env

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Generate .env template for production
 */
export function generateEnvTemplate(cfg: DeploymentConfig): string {
  return `# dustCMS Production Environment
# Generated by setup wizard

# Server configuration
PORT=${cfg.port}
BASE_DOMAIN=${cfg.domain}
NODE_ENV=production

# Data directory (absolute path)
DATA_DIR=${cfg.dataDir}

# Session secret (IMPORTANT: Change this to a random string!)
# Generate with: openssl rand -base64 32
SESSION_SECRET=CHANGE_THIS_TO_RANDOM_STRING
`;
}

/**
 * Generate deployment instructions
 */
export function generateDeploymentInstructions(cfg: DeploymentConfig): string {
  return `
╔═══════════════════════════════════════════════════════════════╗
║          dustCMS Production Deployment Instructions           ║
╚═══════════════════════════════════════════════════════════════╝

Configuration files have been generated in the 'deployment' directory:
  • Caddyfile           - Caddy reverse proxy configuration
  • dustcms.service     - systemd service for auto-start
  • .env.production     - Production environment template

📋 Deployment Steps:

1. Build the standalone binary:
   $ bun run build

2. Set up the production environment:
   $ sudo mkdir -p /opt/dustcms
   $ sudo cp cms-server /opt/dustcms/
   $ sudo cp deployment/.env.production /opt/dustcms/.env
   $ sudo mkdir -p ${cfg.dataDir}
   $ sudo chown -R ${cfg.user}:${cfg.user} /opt/dustcms ${cfg.dataDir}

3. Update the session secret in /opt/dustcms/.env:
   $ sudo -u ${cfg.user} bash -c "openssl rand -base64 32 | sed 's/^/SESSION_SECRET=/' >> /opt/dustcms/.env"

4. Install and configure Caddy:
   $ sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
   $ curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
   $ curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
   $ sudo apt update
   $ sudo apt install -y caddy

5. Deploy Caddy configuration:
   $ sudo cp deployment/Caddyfile /etc/caddy/Caddyfile
   $ sudo mkdir -p /var/log/caddy
   $ sudo chown caddy:caddy /var/log/caddy
   $ sudo systemctl reload caddy

6. Install and start the dustCMS service:
   $ sudo cp deployment/dustcms.service /etc/systemd/system/
   $ sudo systemctl daemon-reload
   $ sudo systemctl enable dustcms
   $ sudo systemctl start dustcms

7. Check service status:
   $ sudo systemctl status dustcms
   $ sudo journalctl -u dustcms -f

8. Configure DNS:
   • Add an A record for ${cfg.domain} pointing to your server IP
   • Add a wildcard A record for *.${cfg.domain} pointing to your server IP

9. Configure firewall (if using ufw):
   $ sudo ufw allow 80/tcp
   $ sudo ufw allow 443/tcp
   $ sudo ufw enable

🎉 Your dustCMS instance will be available at:
   • Admin: https://${cfg.domain}/admin/login
   • Tenants: https://tenant-slug.${cfg.domain}

📝 Useful commands:
   • View logs: sudo journalctl -u dustcms -f
   • Restart: sudo systemctl restart dustcms
   • Stop: sudo systemctl stop dustcms
   • Reload Caddy: sudo systemctl reload caddy

💡 Tips:
   • Caddy automatically obtains and renews SSL certificates
   • All HTTP traffic is automatically redirected to HTTPS
   • Logs are stored in /var/log/caddy/
   • Service logs are in systemd journal
`;
}

/**
 * Save deployment configuration files
 */
export function saveDeploymentFiles(cfg: DeploymentConfig): void {
  const deploymentDir = join(process.cwd(), 'deployment');

  // Create deployment directory
  const { mkdirSync, existsSync } = require('fs');
  if (!existsSync(deploymentDir)) {
    mkdirSync(deploymentDir, { recursive: true });
  }

  // Generate and save files
  writeFileSync(
    join(deploymentDir, 'Caddyfile'),
    generateCaddyfile(cfg)
  );

  writeFileSync(
    join(deploymentDir, 'dustcms.service'),
    generateSystemdService(cfg)
  );

  writeFileSync(
    join(deploymentDir, '.env.production'),
    generateEnvTemplate(cfg)
  );

  writeFileSync(
    join(deploymentDir, 'DEPLOYMENT.md'),
    generateDeploymentInstructions(cfg)
  );

  console.log(`\n✓ Deployment files saved to: ${deploymentDir}/`);
}
